### ISSUE TITLE
Set `transform` to "none" when all transform props are default

### ISSUE THREAD

**Issue by InventingWithMonster** [Popmotion/stylefire#11]
In https://github.com/Popmotion/stylefire/blob/master/src/css/render.ts return set transform string to "none" if all transform props are default, as transforms create new stacking contexts which can cause layout issues if persisted.

**Comment by jptissot** [comment]
I think this was fixed in the latest version ? Would it be possible to use stylefire 1.2.12 in Popmotion ?

**Comment by InventingWithMonster** [comment]
Yeah it should automatically use it if you do a fresh npm install. Will need a republish for script iclude

**Comment by InventingWithMonster** [comment]
Yeah it should automatically use it if you do a fresh npm install. Will need a republish for script iclude
