### ISSUE TITLE
First issue, gotta be 'ol IE!

### ISSUE THREAD

**Issue by timothyallan** [Popmotion/stylefire#2]
So IE/Edge has zilch support for SVGGraphicsElement 
https://developer.mozilla.org/en-US/docs/Web/API/SVGGraphicsElement

Actually, it says that Edge does, but Edge generates the same error as IE I've found.

So, popmotion doesn't work in IE, as PM uses stylefire, which uses SVGGraphicsElement, and IE dies on this line with `SVGGraphicsElement is undefined` https://github.com/Popmotion/stylefire/blob/dc74faf0614741f7a84291e3f87407d216087bec/src/index.ts#L11

Some logic/flag set like 
```
supportsSVG() {
    return (typeof SVGGraphicsElement !== undefined);
}
```

might fix it up?

**Comment by InventingWithMonster** [comment]
Hey man thanks for opening this. I haven’t been getting notifications on his repo for some reason I missed it. Someone’s got a PR in for it so I’ll have a fix out by the end of the day.
