### ISSUE TITLE
Version 2.1.0 published on npm is broken

### ISSUE THREAD

**Issue by HyperMaxime** [Popmotion/stylefire#24]
The code that was published with this version imports from `framesync` assuming it has a default export, but it doesn't (at least not in the version being installed through the `package.json`).

This broke our application with the following message:
```
"export 'default' (imported as 'sync') was not found in 'framesync'
 @ ./node_modules/popmotion/dist/popmotion.es.js
 @ ./node_modules/popmotion-pose/dist/popmotion-pose.es.js
 @ ./node_modules/react-pose/dist/react-pose.es.js
```

Our current workaround is to override this dependency by adding `stylefire` version `2.0.7` to our application's `package.json` file.

**Comment by InventingWithMonster** [comment]
Have you installed `framesync` separately?

**Comment by HyperMaxime** [comment]
No the only direct dependency in our `package.json` depending on it is `popmotion`, of which we currently have version `8.3.3` specified.

**Comment by InventingWithMonster** [comment]
Could you try updating to `popmotion@8.4.0` and `stylefire@2.1.0` please?

**Comment by HyperMaxime** [comment]
I upgraded to `popmotion@8.4.0` and removed `stylefire` as a direct dependency from our `package.json` and it works like a charm, thereby closing this issue. 

Thanks for the quick response and helpful suggestion!
